# En este fichero de extensión toml comentar/descomentar una linea es precederla/no precederla del símbolo #.
# Las distintas partes de la pagina web existen por la existencia de configuraciones, o porque estas tengan un interruptor a "true".
# Este fichero hugo.toml es el responsable de generar la página de inicio del sitio web.
# Lea cuidadosamente las opciones y modifiquelas para ver su efecto.

# Comente o descomente la variable baseurl según se encuentre desarrollando este sitio web en su ordenador o lo esté desplegando en github o un server de la Universidad de Sevilla.

# baseurl = "http://localhost" 
# baseurl = "https://personal.us.es/rjsevillano"
baseurl = "https://jescuderosic.github.io/personal-US-hugo-universal/"


title = "rjsevillano"
theme = "hugo-universal-theme"
themesDir = "./themes"
languageCode = "es-es"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "es"

# number of words of summarized post content (default 70)
summaryLength = 50

# not pluralize title pages by default
pluralizelisttitles = false

[services]
    # Enable comments by entering your Disqus shortname
    [services.disqus]
        shortname = "jescuderosic"
    # Enable Google Analytics by entering your tracking code
    [services.googleAnalytics]
        id = ""

# Define the number of posts per page
[pagination]
    pagerSize = 10

# Main menu
[menu]
[[menu.main]]
    name       = "Inicio"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Currículum"
    identifier = "menu.curriculum"
    url        = "/curriculum/"
    weight     = 2

[[menu.main]]
    parent     = "menu.curriculum"
    name       = "Formación"
    identifier = "menu.formacion"
    url        = "/curriculum/formacion"
    weight     = 1

[[menu.main]]
    parent     = "menu.curriculum"
    name       = "Actividad Docente"
    identifier = "menu.actividaddocente"
    url        = "/curriculum/actividaddocente"
    weight     = 2

[[menu.main]]
    parent     = "menu.curriculum"
    name       = "Investigación"
    identifier = "menu.investigacion"
    url        = "/curriculum/investigacion"
    weight     = 3

[[menu.main]]
    name       = "Publicaciones"
    identifier = "menu.publicaciones"
    url        = "/publicaciones/"
    weight     = 3

[[menu.main]]
    parent     = "menu.publicaciones"
    name       = "Libros"
    identifier = "menu.libros"
    url        = "/publicaciones/libros"
    weight     = 1

[[menu.main]]
    parent     = "menu.publicaciones"
    name       = "Capítulos en Libros"
    identifier = "menu.capituloslibros"
    url        = "/publicaciones/capituloslibros"
    weight     = 2

[[menu.main]]
    parent     = "menu.publicaciones"
    name       = "Artículos en Revistas"
    identifier = "menu.articulosrevistas"
    url        = "/publicaciones/articulosrevistas"
    weight     = 3

[[menu.main]]
    parent     = "menu.publicaciones"
    name       = "Otras Publicaciones"
    identifier = "menu.otraspublicaciones"
    url        = "/publicaciones/otraspublicaciones"
    weight     = 4

[[menu.main]]
    name       = "Docencia"
    identifier = "menu.docencia"
    url        = "/docencia/"
    weight     = 4

[[menu.main]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 5

[[menu.main]]
    name       = "Contacto"
    identifier = "menu.contacto"
    url        = "/contacto/"
    weight     = 6


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/jescuderoSIC/personal-US-hugo-universal"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "X"
    url = "https://x.com"
    pre = "<i class='fab fa-2x fa-x-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:hello@universal.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["cast"]

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "37.38027182"
    longitude = "-5.99111145"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "US"
    date_format = "Monday, 2 de January de 2006"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

# SOBRE NOSOTROS
    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright = "Copyright (c) 2026, Universidad de Sevilla."

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Universal"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Ramón Jiménez Sevillano</strong>
        <br>Facultad de Filología
        <br>Calle Palos de la Frontera, s/n
        <br>41004 - Sevilla
        <br>
        <strong>ESPAÑA</strong>
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Página WEB del Profesor Ramón Jiménez Sevillano</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.biografia]
    enable = true
    title = "Algunos detalles sobre mí"
    texto = """
    <p>Ramón Jiménez Sevillano (Sevilla, 1972) es catedrático de Teoría de la Literatura y Literatura Comparada en la Universidad de Sevilla. Su carrera combina la pasión por la poesía y la pintura con una trayectoria internacional.</p>
    <p>Doctor en Filología, realizó una estancia postdoctoral en la Universidad de Tokio (2002-2004), donde estudió haiku y pintura sumi-e. Fue profesor titular en la Universidad de Sídney (2006-2009), investigando poesía y paisaje en el Pacífico, y profesor visitante en la Universidad de Buenos Aires (2012-2014), donde profundizó en la poesía de Pizarnik y la pintura de Berni.</p>
    <p>A lo largo de esos años fue publicando artículos en revistas de literatura comparada que le dieron proyección nacional e internacional. En 2015 regresó a Sevilla como profesor titular y continuó publicando hasta reunir los méritos suficientes para obtener, en 2023, la cátedra en su facultad de origen. Su obra más conocida es La mirada y el verbo: estéticas comparadas entre Oriente y Occidente (2020).</p>
    """
    foto = "img/profesor.jpg"
    alt = "Foto del profesor Ramón Jiménez Sevillano"

[params.features]
    enable = false
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = true
    cols = 4
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Recién Publicados"
    subtitle = "Libros y artículos publicados recientemente (2025-2026)"

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "A veces un Haiku embellece tu día"
    subtitle = "Un mundo de sufrimiento<br>Y aun así, los cerezos<br>Están floreciendo "
    link_url = "https://themes.gohugo.io/"
    link_text = "Galería de Temas de Hugo"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "anillo web"
    subtitle = "Conjunto de páginas webs de Universidades, Departamentos, Colegas y Amigos con los que comparto trabajo e intereses."

[params.recent_posts]
    enable = true
    title = "El blog de esta página"
    subtitle = "El Blog de esta página contiene sobre todo algunos ejemplos de webs creadas con HUGO, sirve a modo de galeria de ejemplos de lo que se puede hacer y probar en estas páginas."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"

# Añadimos esto para que acepte HTML

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true
    [markup.goldmark.renderer]
      unsafe = true
